# Cloudflare Workers configuration for Bluesky Post Generator
name = "bluesky-skeetgen"
compatibility_date = "2025-07-28"

# Main worker script
main = "api-worker.js"

# Static assets configuration
[assets]
directory = "./site"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
