# Cloudflare Workers configuration for Bluesky Post Generator
name = "bluesky-skeetgen"
compatibility_date = "2025-07-28"

# Static assets configuration
[assets]
directory = "./site"

# Environment variables (if needed in the future)
# [vars]
# API_URL = "https://api.example.com"

# Secrets (if needed in the future)
# [secrets]
# API_KEY = "your-secret-key"

# Custom domains (configure via wrangler domain add)
# [env.production.routes]
# pattern = "yourdomain.com/*"
# zone_name = "yourdomain.com"